# Generated by Django 5.0.1 on 2024-02-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids',
            name='Book_Image',
            field=models.ImageField(default='NA', upload_to='book_image'),
        ),
    ]
