# Generated by Django 5.0.1 on 2024-02-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0002_kids_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='love',
            name='Book_Image',
            field=models.ImageField(default='NA', upload_to='book_image'),
        ),
        migrations.AddField(
            model_name='sci_fyi',
            name='Book_Image',
            field=models.ImageField(default='NA', upload_to='book_image'),
        ),
        migrations.AddField(
            model_name='story',
            name='Book_Image',
            field=models.ImageField(default='NA', upload_to='book_image'),
        ),
    ]
