# Generated by Django 5.0.1 on 2024-02-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0003_love_book_image_sci_fyi_book_image_story_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='love',
            name='Book_Image',
            field=models.ImageField(default='NA', upload_to='book_image2'),
        ),
        migrations.AlterField(
            model_name='sci_fyi',
            name='Book_Image',
            field=models.ImageField(default='NA', upload_to='book_image1'),
        ),
        migrations.AlterField(
            model_name='story',
            name='Book_Image',
            field=models.ImageField(default='NA', upload_to='book_image3'),
        ),
    ]
