# Generated by Django 5.0.1 on 2024-03-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0004_alter_love_book_image_alter_sci_fyi_book_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids',
            name='Book_Description',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='kids',
            name='Book_Price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='love',
            name='Book_Description',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='love',
            name='Book_Price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sci_fyi',
            name='Book_Description',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='sci_fyi',
            name='Book_Price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='Book_Description',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='story',
            name='Book_Price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
